/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import Model.Model_Menu;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setOpaque(false);
//        listMenu1.setOpaque(false);
//        init();
    }
//    private void init(){
//        listMenu1.addItem(new Model_Menu("1","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("2","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("3","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("4","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("5","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("6","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("7","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("8","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("9","Dashboard",Model_Menu.MenuType.Menu));
//        listMenu1.addItem(new Model_Menu("","Dashboard",Model_Menu.MenuType.Emty));
//        listMenu1.addItem(new Model_Menu("","Dashboard",Model_Menu.MenuType.Emty));
//        listMenu1.addItem(new Model_Menu("10","Dashboard",Model_Menu.MenuType.Menu));
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_moving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        Panel_moving.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/IconRuou (1).png"))); // NOI18N
        jLabel1.setText(" OSAKE");

        javax.swing.GroupLayout Panel_movingLayout = new javax.swing.GroupLayout(Panel_moving);
        Panel_moving.setLayout(Panel_movingLayout);
        Panel_movingLayout.setHorizontalGroup(
            Panel_movingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_movingLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        Panel_movingLayout.setVerticalGroup(
            Panel_movingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_movingLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(488, 488, 488))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_moving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_moving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gra = new GradientPaint(0, 0, Color.decode("#0b8793"), 0 , getHeight(), Color.decode("#360033"));
        g2.setPaint(gra);
        
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15 , 15 );
        g2.fillRect(getWidth()-20, 0, getWidth(), getHeight());
        super.paintChildren(g); 
    }
private int x;
private int y;
public void initMoving(JFrame fram){
    Panel_moving.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            x=e.getX();
            y = e.getY();
        }
        
    });
    Panel_moving.addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            fram.setLocation(e.getXOnScreen()-x, e.getYOnScreen()-y);
        }
        
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_moving;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
